import { MonsterData } from './types';

export const MONSTERS: MonsterData[] = [
  {
    id: 'warrior',
    name: 'Goblin Warrior',
    title: 'THE GRUNT BRUISER',
    role: 'Frontline Vanguard / Melee Brawler',
    tier: 'COMMON THREAT',
    difficulty: 2,
    primaryColor: '#e07a38',
    accentColor: '#ffd166',
    bgGlow: 'rgba(224, 122, 56, 0.25)',
    idleImage: 'assets/monsters/warrior_idle.png',
    actionImage: 'assets/monsters/warrior_action.png',
    actionName: 'Skullcrusher Smash',
    actionType: 'HEAVY IMPACT',
    description: 'Armored with hardened scrap metal and horned cap. Rushes enemies with reckless, high-stamina sweeping strikes.',
    quote: '"Me hit first, me smash skull, me take shiny loot!"',
    weapon: 'Spiked Heavy War-Club',
    outfits: ['Scrap Iron Mail', 'Horned Helmet', 'Brawler Wraps'],
    stats: {
      hp: 75,
      atk: 70,
      def: 60,
      spd: 45,
    },
  },
  {
    id: 'archer',
    name: 'Goblin Archer',
    title: 'NEEDLE EYE SNIPER',
    role: 'Ranged Marksmanship / Scout',
    tier: 'UNCOMMON SCOUT',
    difficulty: 3,
    primaryColor: '#48bb78',
    accentColor: '#9ae6b4',
    bgGlow: 'rgba(72, 187, 120, 0.25)',
    idleImage: 'assets/monsters/archer_idle.png',
    actionImage: 'assets/monsters/archer_action.png',
    actionName: 'Piercing Snipe',
    actionType: 'CRITICAL RANGED',
    description: 'Specializes in high-velocity poisoned arrows from the tree canopy. Quick evasion and pin-point accuracy.',
    quote: '"Twitch once in bushes, catch feather through forehead."',
    weapon: 'Curved Yew Bow & Barbed Quiver',
    outfits: ['Ranger Leather', 'Green Feathers', 'Camouflage Cloak'],
    stats: {
      hp: 45,
      atk: 80,
      def: 35,
      spd: 88,
    },
  },
  {
    id: 'shaman',
    name: 'Goblin Shaman',
    title: 'VOID CALLER',
    role: 'Arcane Occultist / Horde Buffer',
    tier: 'ELITE SORCERER',
    difficulty: 4,
    primaryColor: '#9f7aea',
    accentColor: '#d6bcfa',
    bgGlow: 'rgba(159, 122, 234, 0.28)',
    idleImage: 'assets/monsters/shaman_idle.png',
    actionImage: 'assets/monsters/shaman_action.png',
    actionName: 'Bloodcurse Incantation',
    actionType: 'DARK HEX / AOE',
    description: 'Draped in ritualistic bone robes and a billowing 3D cloak. Channels primal ancestral spirits to terrorize foes.',
    quote: '"Spirits whisper in shadows... they hunger for your blood."',
    weapon: 'Antler Totem Staff & Ritual Skull',
    outfits: ['Grand Mystic Cowl', 'Billowing 3D Cloak', 'Runic Beads'],
    stats: {
      hp: 55,
      atk: 90,
      def: 40,
      spd: 60,
    },
  },
  {
    id: 'rogue',
    name: 'Goblin Rogue',
    title: 'SHADOW VIPER',
    role: 'Stealth Infiltrator / Dual Executioner',
    tier: 'ELITE ASSASSIN',
    difficulty: 4,
    primaryColor: '#38bdf8',
    accentColor: '#7dd3fc',
    bgGlow: 'rgba(56, 189, 248, 0.25)',
    idleImage: 'assets/monsters/rogue_idle.png',
    actionImage: 'assets/monsters/rogue_action.png',
    actionName: 'Flurry Backstab',
    actionType: 'LETHAL BURST',
    description: 'Blends into total darkness. Striking with twin serrated daggers before evaporating back into the mist.',
    quote: '"You will never hear the step that ends you."',
    weapon: 'Twin Curved Obsidian Daggers',
    outfits: ['Shadow Veil', 'Padded Moccasins', 'Bandolier of Blades'],
    stats: {
      hp: 50,
      atk: 92,
      def: 42,
      spd: 95,
    },
  },
  {
    id: 'ogre',
    name: 'Mace Ogre',
    title: 'ANCIENT TITAN OF RUIN',
    role: 'Calamity World Boss / Behemoth',
    tier: 'LEGENDARY BOSS',
    difficulty: 5,
    primaryColor: '#ef4444',
    accentColor: '#fca5a5',
    bgGlow: 'rgba(239, 68, 68, 0.35)',
    idleImage: 'assets/monsters/ogre_idle.png',
    actionImage: 'assets/monsters/ogre_action.png',
    actionName: 'Cataclysmic Earthshaker',
    actionType: 'GROUND SURGE / OBLITERATION',
    description: 'A colossal apex predator of raw primal muscle. Wields a devastating 16-flanged iron mace capable of sundering the earth itself.',
    quote: '"CRUSH! SHATTER! ALL BONES TURN TO DUST!"',
    weapon: '16-Flanged Colossal Spiked Mace',
    outfits: ['Primitive Leather Kilt', 'War Skull Medallion', 'Tribal Markings'],
    stats: {
      hp: 100,
      atk: 98,
      def: 92,
      spd: 40,
    },
  },
];
